version: '3.8'

services:
  backend:
    build: .
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      # Pass your environment variables here or use an env_file
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    env_file:
      - .env

  frontend:
    build: .
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_PROJECT=TravelWAI_MSc
      # Include other required env vars here
    env_file:
      - .env
    depends_on:
      - backend
